In [211]:
from sklearn.datasets import load_iris
import numpy as np

x = load_iris().data
x = np.c_[x, np.ones(x.shape[0])]
y = load_iris().target

In [212]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=29)

x_train.shape

(112, 5)

In [213]:
def learning_schedule(t):
    return 5 / (t + 50)

def SGD(X, y, n_epoch, eta):
    theta = np.random.rand(X.shape[1], 1)
    print(theta)
    m = X.shape[0]
    for epoch in range(1, n_epoch):
        for n in range(m):
            r = np.random.randint(0, m-1)
            xi, yi = X[r:r+1], y[r:r+1]
            diff = xi.T @ ((xi @ theta) - yi)
            eta = learning_schedule(epoch * m + n)
            theta = theta - (diff * eta)
    return theta

theta = SGD(x_train, y_train, 50, 0.1)

print(theta)

preds = x_test @ theta

[[ 0.49200034]
 [ 0.61002333]
 [ 0.80372204]
 [ 0.12144007]
 [ 0.03269604]]
[[-0.17092451]
 [ 0.05433827]
 [ 0.42032977]
 [ 0.24853721]
 [-0.04787395]]


In [214]:
preds = np.rint(preds)

In [215]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, preds)

0.97368421052631582

In [216]:

def BGD(X, y, n_epoch, eta):
    theta = np.random.rand(X.shape[1], 1)
    m = len(X)
    for i in range(n_epoch):
        gradients = 2/m * X.T @ ((X @ theta) - y)
        theta = theta - eta * gradients
    return np.mean(theta, axis=1).reshape(X.shape[1], 1)

theta_BGD = BGD(x_train, y_train, 5000, 0.01)

print(theta_BGD)

[[ 0.02504654]
 [-0.01634352]
 [-0.02648509]
 [ 0.034934  ]
 [ 0.88059331]]


In [217]:
preds = x_test @ theta_BGD
preds = np.rint(preds)
accuracy_score(y_test, preds)

0.34210526315789475

In [ ]:
# theta_NORM = (np.linalg.inv(x_train.T @ x_train) @ x_train.T @ y_train).reshape((5, 1))