In [2]:
from sklearn.datasets import load_iris
import numpy as np

x = load_iris().data
x = np.c_[x, np.ones(x.shape[0])]
y = load_iris().target

In [3]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=29)

x_train.shape

(112, 5)

In [87]:
def learning_schedule(t):
    return 5 / (t + 50)

def SGD(X, y, n_epoch, eta):
    theta = np.random.rand(X.shape[1], 1)
    print(theta)
    m = X.shape[0]
    for epoch in range(1, n_epoch):
        for n in range(m):
            r = np.random.randint(0, m-1)
            xi, yi = X[r:r+1], y[r:r+1]
            diff = xi.T @ ((xi @ theta) - yi)
            eta = learning_schedule(epoch * m + n)
            theta = theta - (diff * eta)
    return theta

theta = SGD(x_train, y_train, 50, 0.1)

print(theta)

preds = x_test @ theta

[[ 0.87485461]
 [ 0.07824321]
 [ 0.59018649]
 [ 0.49583709]
 [ 0.95820811]]
[[-0.05926657]
 [-0.23835602]
 [ 0.17448713]
 [ 0.61293062]
 [ 0.6548289 ]]


In [88]:
preds = np.rint(preds)

In [89]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, preds)

0.97368421052631582

In [104]:
# def BGD(X, y, n_epoch, eta):
#     theta = np.random.rand(X.shape[1], 1)
#     m = len(X)
#     for i in range(n_epoch):
#         theta = np.linalg.inv(eight.T @ eight) @ eight.T @ y
#         theta = theta - eta * gradients
#     return theta

theta_BGD = (np.linalg.inv(x_train.T @ x_train) @ x_train.T @ y_train).reshape((5, 1))

# theta_BGD = BGD(x_train, y_train, 50, 0.001)

print(theta_BGD)

[[-0.03292821]
 [-0.11230663]
 [ 0.17040324]
 [ 0.65507335]
 [ 0.11429235]]


In [105]:
preds = x_test @ theta_BGD
preds = np.rint(preds)
accuracy_score(y_test, preds)

0.94736842105263153